### ISSUE TITLE
[Question] Vue version ETA?

### ISSUE THREAD

**Issue by 19peaches** [cruip/tailwind-dashboard-template#1]
This is such a beautiful template, when do you think the Vue version will be available?

Will it be written in Vue 3 or 2?

If it's in Vue 3 will it make heavy use of composition, or options API's? 

Thanks, I'm eager to purchase.

**Comment by pasqualevitiello** [comment]
PRO Vue version will be available on cruip.com is a few days. And, sure, it will be written in Vue 3, using the composition API :)

**Comment by pasqualevitiello** [comment]
We’ve just released the Vue.js version of Mosaic on cruip.com 🙌 https://cruip.com/mosaic/
