### ISSUE TITLE
npm WARN mosaic-react@0.1.0 No repository field.

### ISSUE THREAD

**Issue by bigxu** [cruip/tailwind-dashboard-template#14]
~/t/tailwind-dashboard-template git:(main) ✗ npm install
npm WARN mosaic-react@0.1.0 No repository field.
npm WARN mosaic-react@0.1.0 No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @esbuild/linux-loong64@0.14.54 (node_modules/@esbuild/linux-loong64

**Comment by pasqualevitiello** [comment]
Those are just warning that don't prevent the app from working. BTW we'll fix that in the next release.
