### ISSUE TITLE
error about Dynamic require of "tailwindcss/plugin" is not supported

### ISSUE THREAD

**Issue by Michael-indochat** [cruip/tailwind-dashboard-template#15]
i tried to change code to fine error position, i finally find error in postcss.cjs files,
please tell me how can i fix it , thanks

my settings :

postcss.config.cjs
```javascript
import tailwindConfig from "./src/css/tailwind.config.cjs";
import autoprefixer from "autoprefixer";
import tailwind from "tailwindcss";

export default {
  plugins: [tailwind(tailwindConfig), autoprefixer],
};
```

tailwind.config.cjs
<img width="745" alt="CleanShot 2022-10-12 at 12 33 31@2x" src="https://user-images.githubusercontent.com/114893149/195250726-d8486e46-287a-4228-98ef-c2f49ead1973.png">

**Comment by pasqualevitiello** [comment]
Hey Michael, are you experiencing similar issues with the original repository?

**Comment by Michael-indochat** [comment]
i check about the error issue,
finally i  use to ESM module to rewrite setting `tailwind config.js` and `postcss.config.js` ,

but i have a new error about Tailwind IntelliSense plugin error,
**this error let me couldn't use Tailwind IntelliSense,**

i put my `Tailwind.config.js` , `postcss.config.js` code in here,
i hope you can help me to find solved direction , thanks you apply

- vscode tailwind css intellisense error image:
  <img width="490" alt="CleanShot 2022-10-13 at 12 10 50@2x" src="https://user-images.githubusercontent.com/114893149/195564267-8062aecf-0e50-437b-a6f3-95ba7500906b.png">
- my tailwind.config.js
  <img width="801" alt="CleanShot 2022-10-13 at 12 11 12@2x" src="https://user-images.githubusercontent.com/114893149/195564566-4e23728d-7aeb-4493-8b85-87c0d7e74c88.png">
- postcss.config.js
  <img width="735" alt="CleanShot 2022-10-13 at 17 47 53@2x" src="https://user-images.githubusercontent.com/114893149/195564667-2b4c2a87-bda3-49e1-904a-a40f759cb934.png">

**Comment by pasqualevitiello** [comment]
Hey Michael, are you experiencing similar issues with the original repository?

**Comment by Michael-indochat** [comment]
Yes, I have try your repo,
but I have changed some styles,
I will put my public repo in here later, please help me to find this error solution, thanks a lot

**Comment by Michael-indochat** [comment]
my repo : https://github.com/Michael-indochat/tailwind-plugin-error

**Comment by pasqualevitiello** [comment]
Gotcha! I had a look at your repo: tracking the error can be a time-consuming task because that's a custom version of the template, and I am afraid I can't provide support at the moment. Hope you can understand!
