### ISSUE TITLE
nothing loads in demo

### ISSUE THREAD

**Issue by diomed** [cruip/tailwind-dashboard-template#21]
demo loads only main page

whatever else link I select, it's just blank

**Comment by pasqualevitiello** [comment]
Hi @diomed! This free repository only includes one page from our premium template, which offers an extensive collection of features. The[ premium Tailwind Admin Dashboard](https://cruip.com/mosaic/) comes with over 50 pages and numerous components!

**Comment by idk-floppy** [comment]
> Hi @diomed! This free repository only includes one page from our premium template, which offers an extensive collection of features. The[ premium Tailwind Admin Dashboard](https://cruip.com/mosaic/) comes with over 50 pages and numerous components!

So why don't link it there too, or atleast give the user a message that "Hey, if you want to see this page, click here!" or something? Would be.. Logical, no?
