### ISSUE TITLE
Dropdown not working on team menu.

### ISSUE THREAD

**Issue by binotby** [cruip/tailwind-dashboard-template#4]
![image](https://user-images.githubusercontent.com/32414473/125336465-025a8700-e378-11eb-9867-c5cfe37a4489.png)
hi i found a bug when i click on team menu nothing happens

**Comment by pasqualevitiello** [comment]
Actually it's not a bug, since it's a link and there isn't any Team page in Mosaic Lite :)
That comes with the premium version: https://cruip.com/demos/mosaic/

**Comment by binotby** [comment]
Thankyou @pasqualevitiello
