### ISSUE TITLE
dropdown.current is null

### ISSUE THREAD

**Issue by aajmot** [cruip/tailwind-dashboard-template#5]
![image](https://user-images.githubusercontent.com/9851114/147590722-b7f7fc9d-92e0-40f2-b2ad-0209eae9836c.png)

While clicked on logout link it's throwing error.

![image](https://user-images.githubusercontent.com/9851114/147590798-9062de2e-211b-496e-a97f-db3080c3a8e5.png)

**Comment by aajmot** [comment]
I have resolve this issue using 

` if (!dropdownOpen || dropdown?.current?.contains(target) || trigger?.current?.contains(target))`

now getting below warning in console.
![image](https://user-images.githubusercontent.com/9851114/147591971-e3c2ca81-1e1e-465f-8f34-352b5d5a2cee.png)

**Comment by pasqualevitiello** [comment]
Did you update any dependencies maybe?

**Comment by aajmot** [comment]
I am totally new in react and just started with your template, really nice and the issue was for some type and after fixing this warning is gone now.
Thanks for making this template.
Thank you once again.

**Comment by pasqualevitiello** [comment]
Thank you for your kind words :)
