### ISSUE TITLE
md breakpoint is not working

### ISSUE THREAD

**Issue by phungchiminhquang** [cruip/tailwind-dashboard-template#6]
I am a newbie in using a template and tailwindcss. 
1. I just add a **md** breakpoint into my Dashboard.js file and realise it didn't work. it still works on my project( tailwindcss + reactJs).

![image](https://user-images.githubusercontent.com/58564617/148053111-b7292345-8412-4ff8-bbf6-f73cf758f9d3.png)

2. After I stretch in and out the width of the browser, the DashboarCard seems to go wrong, it's stretched and does not return to its original size anymore.
![image](https://user-images.githubusercontent.com/58564617/148053049-86064b12-8e45-4ca5-95b8-887b16b7cb00.png)

Note: I just downloaded the template and adjusted the package.json
from
`"scripts": {
    "start": "TAILWIND_MODE=watch craco start",`
to
`"scripts": {
    "start": "set PORT=3002 &&craco start",`
and I run `npm start` like i usually do to run it

**Comment by pasqualevitiello** [comment]
1) 
```
Note: I just downloaded the template and adjusted the package.json
from
"scripts": { "start": "TAILWIND_MODE=watch craco start",
to
"scripts": { "start": "set PORT=3002 &&craco start",
and I run npm start like i usually do to run it
```
This is why any change you make in your file is not reflected in the browser :) 

2) That's normal, because it's a grid layout and when you shrink the browser window, the 3rd card gets the height of the 4th one. As a consequence, when you enlarge the browser window again, cards 1 and 2 get the height of the card nr. 3. Not a big deal, since users won't need to stretch and enlarge the browser window continuously when navigating.

**Comment by phungchiminhquang** [comment]
1. I have to adjust my package.json to make it run without error. I hope you can show me the right way to run it without adjusting the package.json, I have spent so much time finding the way( including install postcss postcss-CLI) to run without adjusting pakage.json but nothing works. Thank you very much
2. I adjust the in **sm** breakpoint to `justify-end` and it does take effect on the browser on save. I add `xs:justify-start` and it also works fine.

**Comment by pasqualevitiello** [comment]
Do you have any deployed version of your app to show?

**Comment by phungchiminhquang** [comment]
Sorry for the late response. I don't have any deployed version :(( . I've begun to know about postcss, craco, sass and tailwind 3 days ago. I've never used it before. I don't know how to make it work together. Hope you can guide me a little bit because I really love your template (I've seen a few React template out there). Thank you very much.

**Comment by pasqualevitiello** [comment]
Use the Chrome inspector to check if the `md:justify-end` exists in your CSS file. If so, it means  that the preprocessor is working properly, and the class is not taking effect for any other reason. Hope that helps :)
