### ISSUE TITLE
Making the sidebar collapsible

### ISSUE THREAD

**Issue by dikum** [cruip/tailwind-dashboard-template#7]
Thanks for the work. Could you please make the sidebar collapsible?

**Comment by pasqualevitiello** [comment]
Actually sidebar **is** collabsible :)  

![Screen Shot on 2022-02-16 at 11:22:01](https://user-images.githubusercontent.com/2683512/154244872-e138f564-1732-41cd-a38b-6ce448f8118c.png)

**Comment by pasqualevitiello** [comment]
Try resizing the browser window :)

**Comment by dikum** [comment]
It gets visible after resizing, Is there a way to make it collapsible even with fullscreen?

**Comment by dikum** [comment]
Thanks! In my case, I'll need the space on the whole screen.

Thank you.
