### ISSUE TITLE
Permission to release a tutorial

### ISSUE THREAD

**Issue by espoal** [cruip/tailwind-dashboard-template#8]
Hello Everyone,

super nice work. I liked it so much I would like to write a tutorial on how to build a full stack app with your theme.

You can see the seed of my work [here](https://github.com/espoal/esm-pwa), a brief list of features 
- Ecmascript modules
- PWA, installable and working offline
- Serverless environment for the backend
- Authentication (firebase, metamask, ...)

I would like to ask you permission to release an open source tutorial. I have also made some small improvements that maybe can be backported in the commercial theme? I think the tutorial could add value to your offer.

**Comment by pasqualevitiello** [comment]
Hello Alberto,

I think that's totally fine, as long as you don't include any of the pages or components that come with the premium version.

I also love the idea of a tutorial: where that'd be published? 

Cheers!

**Comment by espoal** [comment]
Hey Pasquale :)

thank you for the quick reply :) 

The tutorial would be published on GitHub, free of charge and open source. I would obviously allow you to link it or integrate it in your offer.

The only commercial page I would like to use is the login page, because I think auth is a very important part of a tutorial:
- I Created an Auth provider component [here](https://github.com/espoal/esm-pwa/blob/main/pkgs/auth/AuthProvider.mjs)
- [Here](https://github.com/espoal/esm-pwa/blob/main/pkgs/app/index.mjs) is auth-protected routing

Worst case I can copy a login page from somewhere, to show support for microfrontends.

I would be willing to let you integrate my code in your package.

Also:
- I'm resolving the CSS config at build time [here](https://github.com/espoal/esm-pwa/blob/main/libs/tailwind/build.mjs), shaving a lot of packages out of the build artifact
- Is there a changelog for the commercial themes, so I  can know what to update / import in our project?

**Comment by pasqualevitiello** [comment]
Hello again,

I've discussed it with Davide (Cruip co-founder) and, yes, you can use the login page for your custom Mosaic version :) 

About point 2, unfortunately we don't have a detailed changelog. Every time we've released a major update, there were hundreds of file with changes, and migrating to a newer version would be a long and frustrating process even in presence of a changelog. This is why we've just listing changes, and not the list of all changed file. But I know that we'd likely find a better solution for developers who want to keep their app up to date.

About point 3, thank you for your offer but currently we're tight on time and we are unable to work on custom requests, I am sorry. But let's keep in touch!

**Comment by espoal** [comment]
Thank you very much Pasquale. 

About releases: maybe you could invite your premium user to a private github repo? 

I finished the seed version [here](https://github.com/espoal/esm-pwa). Features are:

- Charts feed from an API
- Authentication
- PWA 
- Offline first

In the next month I will probably create a new repo and release the documentation. 

I will create a new ticket as soon as the tutorial is ready :)
